//in this file schema is defined using mongoose 
//since there are at max 73 columns so i have taken till c73

var mongoose = require('mongoose');

var Schema = mongoose.Schema;

var tradeSchema = new Schema({

  C1:{type:String},
  C2:{type:String},
  C3:{type:String},
  C4:{type:String},
  C5:{type:String},
  C6:{type:String},
  C7:{type:String},
  C8:{type:String},
  C9:{type:String},
  C10:{type:String},
  C11:{type:String},
  C12:{type:String},
  C13:{type:String},
  C14:{type:String},
  C15:{type:String},
  C16:{type:String},
  C17:{type:String},
  C18:{type:String},
  C19:{type:String},
  C20:{type:String},
  C21:{type:String},
  C22:{type:String},
  C23:{type:String},
  C24:{type:String},
  C25:{type:String},
  C26:{type:String},
  C27:{type:String},
  C28:{type:String},
  C29:{type:String},
  C30:{type:String},
  C31:{type:String},
  C32:{type:String},
  C33:{type:String},
  C34:{type:String},
  C35:{type:String},
  C36:{type:String},
  C37:{type:String},
  C38:{type:String},
  C39:{type:String},
  C40:{type:String},
  C41:{type:String},
  C42:{type:String},
  C43:{type:String},
  C44:{type:String},
  C45:{type:String},
  C46:{type:String},
  C47:{type:String},
  C48:{type:String},
  C49:{type:String},
  C50:{type:String},
  C51:{type:String},
  C52:{type:String},
  C53:{type:String},
  C54:{type:String},
  C55:{type:String},
  C56:{type:String},
  C57:{type:String},
  C58:{type:String},
  C59:{type:String},
  C60:{type:String},
  C61:{type:String},
  C62:{type:String},
  C63:{type:String},
  C64:{type:String},
  C65:{type:String},
  C66:{type:String},
  C67:{type:String},
  C68:{type:String},
  C69:{type:String},
  C70:{type:String},
  C71:{type:String},
  C72:{type:String},
  C73:{type:String}

});

module.exports = mongoose.model('Trades', tradeSchema  );
//trades is collection name